---
title: "B2 NO Simulation"
output: html_notebook
---

Need arrival and departure distribution, then cobble together some quick
analysis of how this affects ward count, wait time, etc.

```{r}
library(tidyverse)
library(lubridate)
library(nycflights13)
library(RODBC)
library(ggplot2)

B2NO_Demand <- tibble(Year = rep(2017, 38),
       Month = rep(4:7, c(12, 6, 8, 12)),
       Day = c(10, 11, 12, 13, 14, 17, 19, 20, 21, 24, 25, 28, 
               10, 11, 12, 16, 22, 31, 
               1, 6, 8, 9, 26, 27, 29, 30, 
               3, 7, 10, 11, 12, 18, 19, 20, 21, 24, 25, 26),
       Wait = c(2, 1, 4, 3, 3, 1, 1, 0, 0, 2, 2, 4,
                2, 1, 2, 5, 3, 3,
                3, 2, 6, 5, 7, 10, 3, 3,
                3, 0, 2, 1, 1, 1, 1, 1, 1, 4, 4, 5),
       Census = c(16, 14, 15, 14, 15, 16, 16, 13, 14, 14, 14, 13,
                  13, 13, 11, 13, 14, 15,
                  11, 12, 14, 11, 11, 10, 11, 11,
                  12, 10, 12, 13, 14, 13, 14, 11, 11, 14, 14, 14))

```

### Grid based bayesian analysis of arrivals, based on Frank's data
```{r}
ngrid <- 1000
l_grid <- seq(from = 0, to = 10, length.out = ngrid)
lambda <- sum(B2NO_Demand$Wait)
prior <- rep(1, ngrid)
likelihood <- dpois(B2NO_Demand$Wait, l_grid)
```
